"""
Hebrew verb extraction pipeline (v2)
Rebuilt to address all requirements in the review:
 1. Compound morph code parsing (verb segment not always first)
 2. Compound lemma parsing with homonym-letter stripping
 3. Aramaic exclusion (H-only)
 4. Full stem-letter map (Hebrew only), scan for unmapped letters
 5. Full 12-category form capture, active/passive participle kept separate
 6. Participle: absolute state only (state code 'a', not 'c'/'d')
 7. Slot preference: bare > suffix-or-prefix > both; vav of wayyiqtol/veqatal exempted
 8. Cantillation stripped (U+0591-05AF), niqqud kept; qamats-gaaya -> patach normalization
 9. Homonym-safe root resolution (meaning text checked manually per root, not just consonants)
 10. Sanity-checked against existing dataset roots before trusting on new ones
"""
import re, glob, json, os, unicodedata
from collections import defaultdict
from pathlib import Path

# Corpus is fetched by fetch_corpus.sh into pipeline/corpus/ by default.
# Override with the HEBREW_VERB_MAP_CORPUS env var if you've put it elsewhere.
_CORPUS_DIR = os.environ.get(
    "HEBREW_VERB_MAP_CORPUS",
    str(Path(__file__).resolve().parent / "corpus"),
)
WLC_GLOB = str(Path(_CORPUS_DIR) / "morphhb" / "wlc" / "*.xml")
LEXICON_PATH = str(Path(_CORPUS_DIR) / "HebrewLexicon" / "HebrewStrong.xml")

# ---- Hebrew verb STEM letters (from HebrewMorphologyCodes.html, "Verb stems (Hebrew)") ----
HEBREW_STEM_MAP = {
    'q': 'qal', 'N': 'niphal', 'p': 'piel', 'P': 'pual', 'h': 'hiphil', 'H': 'hophal',
    't': 'hitpael', 'o': 'polel', 'O': 'polal', 'r': 'hithpolel', 'm': 'poel', 'M': 'poal',
    'k': 'palel', 'K': 'pulal',
    'Q': 'qal_passive', 'l': 'pilpel', 'L': 'polpal', 'f': 'hithpalpel', 'D': 'nithpael',
    'j': 'pealal', 'i': 'pilel', 'u': 'hothpaal', 'c': 'tiphil', 'v': 'hishtaphel',
    'w': 'nithpalel', 'y': 'nithpoel', 'z': 'hithpoel',
}

# ---- Verb conjugation TYPE letters (language-independent) ----
TYPE_MAP = {
    'p': 'perfect', 'q': 'veqatal', 'i': 'yiqtol', 'w': 'wayyiqtol',
    'h': 'cohortative', 'j': 'jussive', 'v': 'imperative',
    'r': 'participle_active', 's': 'participle_passive',
    'a': 'infinitive_absolute', 'c': 'infinitive_construct',
}

CANT = set(range(0x0591, 0x05AF + 1))


def strip_cant(s):
    return ''.join(c for c in s if ord(c) not in CANT)


def normalize_gaaya(s):
    """
    RETIRED as of pipeline v2. A single earlier data point (Gen.35.3, הלך) suggested
    the original dataset converted qamats(05B8)+meteg(05BD) to patach(05B7). Broader
    testing against שמר disproves this as a systematic rule: the existing dataset is
    inconsistent (Job.10.12 and 1Sam.9.24 keep qamats+meteg verbatim; 1Sam.19.2 drops
    the meteg but keeps qamats; only the original הלך case converts to patach). No
    coherent rule exists to replicate -- it was very likely an isolated manual edit or
    error in that one entry, not a pipeline transformation. Per requirement 8 ("keep
    niqqud"), meteg is now preserved as attested. This function is now a no-op, kept
    only so callers don't need to change.
    """
    return s


def clean_heb(raw):
    # OSHB word text embeds literal '/' characters marking morpheme boundaries
    # (prefix/stem/suffix each individually vocalized) -- these are not part of
    # the actual spelling and must be dropped, not just cantillation marks.
    no_slash = raw.replace('/', '')
    result = normalize_gaaya(strip_cant(no_slash))
    # NFC-normalize combining-mark order (dagesh vs. vowel point, etc.). The
    # source XML doesn't consistently use canonical order, but any Hebrew
    # text typed or generated by hand naturally does -- without this, two
    # byte-different-but-visually-and-linguistically-identical strings will
    # wrongly compare as unequal (this caused a wave of false-positive
    # "discrepancies" during the first full-dataset consistency sweep).
    return unicodedata.normalize('NFC', result)


def lemma_matches(lemma_attr, target_numbers):
    """Requirement 2: compound lemma parsing, strip homonym letters."""
    parts = re.split(r'[/\s]+', lemma_attr.strip())
    for p in parts:
        if not p:
            continue
        # strip trailing homonym letter e.g. "1254 a" already split by whitespace above
        # but a part could still be "1254a" without space in rare cases -- handle both
        m = re.match(r'^(\d+)[a-z]?$', p)
        if m and m.group(1) in target_numbers:
            return True
    return False


def parse_morph(morph):
    """
    Requirement 1 & 3: compound morph parsing, Hebrew-only.
    Returns dict with stem_letter, type_letter, person, gender, number, state,
    has_prefix, has_suffix, verb_seg_index -- or None if not a Hebrew verb.
    """
    if not morph.startswith('H'):
        return None  # Aramaic (A) or other -- excluded per requirement 3
    body = morph[1:]
    segs = body.split('/')
    v_idx = None
    for i, seg in enumerate(segs):
        if seg.startswith('V'):
            v_idx = i
            break
    if v_idx is None:
        return None  # not a verb token
    vseg = segs[v_idx][1:]  # drop the 'V'
    prefix_segs = segs[:v_idx]  # raw prefix segments, e.g. ['C'], ['R'], ['Td'], ['C','R'], etc.
    # Suffix segments come in four types (per HebrewMorphologyCodes): Sd
    # (directional he), Sh (paragogic he), Sn (paragogic nun), Sp
    # (pronominal object suffix). Only Sp is a true pronoun object -- the
    # other three are particles attached to the verb, not suffixed pronouns,
    # and must not be flagged as has_suffix.
    suffix_segs = segs[v_idx + 1:]
    has_suffix = any(seg.startswith('Sp') for seg in suffix_segs)

    if len(vseg) == 0:
        return None
    stem_letter = vseg[0]
    rest = vseg[1:]
    if len(rest) == 0:
        return {'stem_letter': stem_letter, 'type_letter': None, 'raw_rest': rest,
                'prefix_segs': prefix_segs, 'has_suffix': has_suffix}
    type_letter = rest[0]
    remainder = rest[1:]
    return {
        'stem_letter': stem_letter, 'type_letter': type_letter, 'remainder': remainder,
        'prefix_segs': prefix_segs, 'has_suffix': has_suffix,
    }


def compute_has_prefix(prefix_segs, category):
    """
    Requirement 7 exception: for wayyiqtol/veqatal, OSHB codes the grammatically
    obligatory sequential vav as a bare conjunction segment 'C' immediately before
    the verb segment. That vav is integral to the conjugation's definition, not an
    optional attachment, so a lone 'C' prefix on these two categories does NOT count
    as has_prefix. Any *additional* or *different* prefix (e.g. ['C','R'], ['Td'],
    a non-'C' segment, or more than one segment) still counts, since that's a real
    proclitic beyond the required vav.
    """
    if not prefix_segs:
        return False
    if category in ('wayyiqtol', 'veqatal') and prefix_segs == ['C']:
        return False
    return True


def decode_pgn(type_letter, remainder):
    """
    For finite verbs (p,q,i,w,h,j,v): remainder is person+gender+number, e.g. '3ms'.
    For participles (r,s): remainder is gender+number+state, e.g. 'msa'.
    For infinitives (a,c): remainder usually empty.
    """
    if type_letter in ('p', 'q', 'i', 'w', 'h', 'j', 'v'):
        # e.g. "3ms", "1cp", "2fs"
        m = re.match(r'^([123x])([cmf])([sp])$', remainder)
        if not m:
            return None
        person, gender, number = m.groups()
        return {'code': f'{person}{gender}{number}'}
    if type_letter in ('r', 's'):
        # gender+number+state e.g. "msa", "fpa", "mpc"
        m = re.match(r'^([cmfb])([sp])([acd])$', remainder)
        if not m:
            return None
        gender, number, state = m.groups()
        return {'code': f'{gender}{number}', 'state': state}
    if type_letter in ('a', 'c'):
        return {'code': 'inf'}
    return None


def scan_root(target_numbers, verbose=True):
    """
    Full corpus scan for a set of target Strong's numbers.
    Returns list of raw attested records + a report of any unmapped stem letters found.
    """
    records = []
    unmapped_stems = defaultdict(list)
    files = sorted(glob.glob(WLC_GLOB))
    for fn in files:
        with open(fn, encoding='utf-8') as f:
            data = f.read()
        for vm in re.finditer(r'<verse osisID="([^"]+)">(.*?)</verse>', data, re.S):
            vid = vm.group(1)
            vtext = vm.group(2)
            for wm in re.finditer(r'<w lemma="([^"]*)"[^>]*morph="([^"]*)"[^>]*>([^<]*)</w>', vtext):
                lemma, morph, heb = wm.groups()
                if not lemma_matches(lemma, target_numbers):
                    continue
                if not morph.startswith('H'):
                    continue  # requirement 3: exclude Aramaic explicitly (defensive; lemma-language should align)
                parsed = parse_morph(morph)
                if parsed is None:
                    continue
                stem_letter = parsed['stem_letter']
                if stem_letter not in HEBREW_STEM_MAP:
                    unmapped_stems[stem_letter].append((vid, morph, heb))
                    continue
                stem_name = HEBREW_STEM_MAP[stem_letter]
                type_letter = parsed.get('type_letter')
                if type_letter is None or type_letter not in TYPE_MAP:
                    continue
                category = TYPE_MAP[type_letter]
                pgn = decode_pgn(type_letter, parsed.get('remainder', ''))
                if pgn is None:
                    continue
                # requirement 6: participles -- absolute state only
                if category in ('participle_active', 'participle_passive'):
                    if pgn.get('state') != 'a':
                        continue
                has_prefix = compute_has_prefix(parsed['prefix_segs'], category)
                records.append({
                    'ref': vid,
                    'heb_raw': heb,
                    'heb': clean_heb(heb),
                    'morph': morph,
                    'stem': stem_name,
                    'category': category,
                    'code': pgn['code'],
                    'has_prefix': has_prefix,
                    'has_suffix': parsed['has_suffix'],
                })
    if verbose and unmapped_stems:
        print("UNMAPPED STEM LETTERS FOUND:", dict(unmapped_stems))
    return records, unmapped_stems


def scan_all(target_numbers, verbose=True):
    """
    Like scan_root, but for many Strong's numbers in a single corpus pass --
    used when verifying (or extracting) many roots at once, since re-parsing
    the whole WLC once per root doesn't scale to a 1000+ root dataset.
    Returns {number: [records]}, unmapped_by_number.
    """
    records_by_number = defaultdict(list)
    unmapped_by_number = defaultdict(list)
    files = sorted(glob.glob(WLC_GLOB))
    for fn in files:
        with open(fn, encoding='utf-8') as f:
            data = f.read()
        for vm in re.finditer(r'<verse osisID="([^"]+)">(.*?)</verse>', data, re.S):
            vid = vm.group(1)
            vtext = vm.group(2)
            for wm in re.finditer(r'<w lemma="([^"]*)"[^>]*morph="([^"]*)"[^>]*>([^<]*)</w>', vtext):
                lemma, morph, heb = wm.groups()
                num = None
                for p in re.split(r'[/\s]+', lemma.strip()):
                    m = re.match(r'^(\d+)[a-z]?$', p)
                    if m and m.group(1) in target_numbers:
                        num = m.group(1)
                        break
                if num is None:
                    continue
                if not morph.startswith('H'):
                    continue
                parsed = parse_morph(morph)
                if parsed is None:
                    continue
                stem_letter = parsed['stem_letter']
                if stem_letter not in HEBREW_STEM_MAP:
                    unmapped_by_number[num].append((vid, morph, heb))
                    continue
                stem_name = HEBREW_STEM_MAP[stem_letter]
                type_letter = parsed.get('type_letter')
                if type_letter is None or type_letter not in TYPE_MAP:
                    continue
                category = TYPE_MAP[type_letter]
                pgn = decode_pgn(type_letter, parsed.get('remainder', ''))
                if pgn is None:
                    continue
                if category in ('participle_active', 'participle_passive') and pgn.get('state') != 'a':
                    continue
                has_prefix = compute_has_prefix(parsed['prefix_segs'], category)
                records_by_number[num].append({
                    'ref': vid, 'heb': clean_heb(heb), 'morph': morph,
                    'stem': stem_name, 'category': category, 'code': pgn['code'],
                    'has_prefix': has_prefix, 'has_suffix': parsed['has_suffix'],
                })
    if verbose and unmapped_by_number:
        print("UNMAPPED STEM LETTERS FOUND:", dict(unmapped_by_number))
    return dict(records_by_number), dict(unmapped_by_number)


# A root's stored stem label doesn't always match the corpus's own
# stem-letter tag -- e.g. כול's pilpel forms are labeled "piel" for
# simplicity, per an explicit earlier decision. Extend this if future roots
# make the same substitution.
STEM_ALIASES = {'piel': ['piel', 'pilpel']}

# (strong, stem, category, code) rows that are deliberately kept even though
# they fail the normal extraction filters -- documented exceptions, not bugs.
KNOWN_EXCEPTIONS = {
    ('H2904', 'pilpel', 'participle_active', 'ms'),  # only attestation is a
    # construct-state participle with a suffix; kept anyway per an explicit
    # decision, since there is no alternative attestation at all.
}


def verify_root(strong, data, records_by_number):
    """
    Cross-check one root's stored forms against a fresh extraction.
    Returns a list of discrepancy dicts (empty if the root is clean).
    `records_by_number` should already include any strong_alt numbers.
    """
    import unicodedata
    nums = [strong[1:]] + [a[1:] for a in data.get('strong_alt', [])]
    records = []
    for n in nums:
        records.extend(records_by_number.get(n, []))
    groups = defaultdict(list)
    for r in records:
        groups[(r['stem'], r['category'], r['code'])].append(r)

    def nfc(s):
        return unicodedata.normalize('NFC', s)

    discs = []
    for stem, stem_obj in data['stems'].items():
        for cat, rows in stem_obj['forms'].items():
            for row in rows:
                if (strong, stem, cat, row['code']) in KNOWN_EXCEPTIONS:
                    continue
                candidate_stems = STEM_ALIASES.get(stem, [stem])
                cands = []
                for cs in candidate_stems:
                    cands.extend(groups.get((cs, cat, row['code']), []))
                match = [c for c in cands if c['ref'] == row['ref']]
                if (match and nfc(match[0]['heb']) == nfc(row['heb'])
                        and match[0]['has_prefix'] == row['has_prefix']
                        and match[0]['has_suffix'] == row['has_suffix']):
                    continue
                best = pick_best(cands) if cands else None
                discs.append({
                    'stem': stem, 'cat': cat, 'code': row['code'],
                    'stored_heb': row['heb'], 'stored_ref': row['ref'],
                    'stored_prefix': row['has_prefix'], 'stored_suffix': row['has_suffix'],
                    'best': best,
                    'ref_exists_at_all': bool(match),
                    'slot_exists_anywhere': bool(cands),
                })
    return discs


def pick_best(records_for_slot):
    """
    Requirement 7: prefer bare > one attachment > both.
    Exception: wayyiqtol/veqatal -- don't penalize the (inherent) vav; there is no
    "prefix" flag contribution from the sequential vav itself since parse_morph's
    has_prefix only fires when the verb segment is NOT the first morph segment
    (i.e. an *additional* proclitic beyond the conjugation's own preformative/vav).
    So no special-casing is actually needed here -- has_prefix already excludes
    the inherent wayyiqtol/veqatal vav by construction. We just rank normally.
    """
    def score(r):
        return (1 if r['has_prefix'] else 0) + (1 if r['has_suffix'] else 0)
    return sorted(records_for_slot, key=lambda r: (score(r), r['ref']))[0]
